version: '3.8'
services:
  mongo:
    image: mongo
    container_name: roomify-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: roomify-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: roomify-client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo-data:
