apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomify-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roomify-server
  template:
    metadata:
      labels:
        app: roomify-server
    spec:
      containers:
      - name: roomify-server
        image: roomify-server:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: roomify-server-service
spec:
  type: ClusterIP
  selector:
    app: roomify-server
  ports:
    - port: 5000
      targetPort: 5000
